name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to registry.apps.timvw.be
      uses: docker/login-action@v1
      with:
        registry: registry.apps.timvw.be
        username: ${{ secrets.REGISTRY_GH_USER }}
        password: ${{ secrets.REGISTRY_GH_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ./deployment/Dockerfile
        tags: |
          docker.io/timvw/rbfacalendar:main
          registry.apps.timvw.be/rbfacalendar:latest
          
